"""The log-line catalogue: every prefix the plugin logs, who writes it, what it means.

    python scripts/log-catalogue.py           # rewrite docs/log-lines.md
    python scripts/log-catalogue.py --check   # stale doc / no meaning / no prefix -> exit 1 (lint.py runs it)

Scans src/ and patcher/ for ManualLogSource calls (LogInfo / LogWarning /
LogError / ...), turns each first argument into a template (string literals
kept, a file's `const string` resolved, a name shown as <name>, anything
else as <..>) and groups the templates by prefix: the leading literal words
up to the first ':', '(', quote, '#', ',', ' -', '. ' or value. The log and
the bridge are the test harness (gotcha 16), so every call starts with a
literal prefix an agent or an e2e check can grep for. Two exceptions
(author, 2026-10-07): a message built elsewhere (a report builder, a
StringBuilder) names the prefix(es) it prints in a `// log: Name` comment on
the call's line or the line above; a line starting with spaces continues
the line above (a report's indented rows) and needs no prefix.

docs/log-lines.md is generated, except the `Meaning:` line under each
prefix: written by hand, kept across regenerations (author, 2026-10-07).
A new prefix gets an empty one and --check fails until it is filled.
Tests: scripts/tests/test_log_catalogue.py.
"""
import argparse
import os
import re
import sys
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = "docs/log-lines.md"
SCAN = ("src", "patcher")
SKIP_DIRS = {"bin", "obj"}
CALL = re.compile(r"\.Log(Info|Warning|Error|Message|Debug|Fatal)\s*\(")
LEVELS = {"Info": "info", "Message": "info", "Debug": "debug",
          "Warning": "warning", "Error": "error", "Fatal": "error"}
LEVEL_ORDER = ("info", "debug", "warning", "error")
CONST = re.compile(r'\bconst\s+string\s+(\w+)\s*=\s*"((?:[^"\\]|\\.)*)"\s*;')
NAME = re.compile(r"^[A-Za-z_][\w.]*$")
PREFIX = re.compile(r"[A-Za-z](?:[A-Za-z0-9 ._/-]|\(\))*?(?=\s*(?::|\((?!\))|'|\"|#|,| - | -> |\. |<|\.?$))")
DECLARE = re.compile(r"//\s*log:\s*(.+?)\s*$")
HEADER = """# Log lines

Generated by `python scripts/log-catalogue.py` from the log calls in
`src/` and `patcher/` - edit only the `Meaning:` lines (kept when it runs
again). Each prefix is what a line in `LogOutput.log` starts with: grep it
to find what a mechanism did (gotcha 16). Templates: `<name>` is a value,
`<..>` an expression; *(declared)* marks a message built elsewhere whose
call names its prefix in a `// log: Name` comment; indented continuation
rows of a report are not listed. `python scripts/log-catalogue.py --check`
(run by `scripts/lint.py`) fails on a stale file, an empty meaning or a log
call with no prefix.
"""


class Problem(object):
    def __init__(self, what, why, fix):
        self.what, self.why, self.fix = what, why, fix

    def __str__(self):
        return "ERROR: %s\nWHY: %s\nFIX: %s" % (self.what, self.why, self.fix)


# ---------------------------------------------------------------- scanning

def mask(text):
    """The text with comments and string / char contents blanked (same length), to find calls in code only."""
    out = list(text)
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if text.startswith("//", i):
            j = text.find("\n", i)
            j = n if j < 0 else j
            out[i:j] = " " * (j - i)
            i = j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            j = n if j < 0 else j + 2
            out[i:j] = [ch if ch == "\n" else " " for ch in text[i:j]]
            i = j
        elif c == '"' or c == "'":
            j = string_end(text, i)
            out[i + 1:j - 1] = " " * (j - i - 2)
            i = j
        else:
            i += 1
    return "".join(out)


def string_end(text, i):
    """Index just past the string or char literal opening at i (handles @"" verbatim)."""
    q = text[i]
    verbatim = q == '"' and i > 0 and text[i - 1] == "@"
    j = i + 1
    while j < len(text):
        if verbatim:
            if text[j] == '"':
                if text.startswith('""', j):
                    j += 2
                    continue
                return j + 1
        elif text[j] == "\\":
            j += 2
            continue
        elif text[j] == q:
            return j + 1
        j += 1
    return len(text)


def first_arg(text, masked, i):
    """The first argument of the call whose '(' ends at i (original text), or None."""
    depth, j = 1, i
    while j < len(masked):
        c = masked[j]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                return text[i:j]
        elif c == "," and depth == 1:
            return text[i:j]
        j += 1
    return None


def operands(arg):
    """The top-level '+' operands of an expression."""
    m = mask(arg)
    parts, depth, start = [], 0, 0
    for j, c in enumerate(m):
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == "+" and depth == 0:
            parts.append(arg[start:j].strip())
            start = j + 1
    parts.append(arg[start:].strip())
    return [p for p in parts if p]


def unescape(body, verbatim):
    if verbatim:
        return body.replace('""', '"')
    return re.sub(r"\\(.)", lambda m: {"n": " ", "t": " ", "r": ""}.get(m.group(1), m.group(1)), body)


def literal(op):
    """The value of a lone string literal operand, else None."""
    m = re.match(r'^(@?)"(.*)"$', op, re.S)
    if m and string_end(op, len(m.group(1))) == len(op):
        return unescape(m.group(2), bool(m.group(1)))
    return None


def template(arg, consts):
    out = []
    for op in operands(arg):
        lit = literal(op)
        if lit is None and op in consts:
            lit = consts[op]
        if lit is not None:
            out.append(lit)
        elif NAME.match(op):
            out.append("<%s>" % op)
        else:
            out.append("<..>")
    text = re.sub(r"(<\.\.>)+", "<..>", re.sub(r"\s+", " ", "".join(out)))
    # A line starting with spaces continues the line above (a report's indented rows).
    return ("  " if text.startswith(" ") and text.strip() else "") + text.strip()


def prefix(tpl):
    """The leading literal words of a template, or None when it starts with a value or spaces."""
    if tpl.startswith(" "):
        return None
    m = PREFIX.match(tpl)
    if not m:
        return None
    p = m.group(0)
    if tpl[len(p):].startswith("<") and " " in p and not p.endswith(" "):
        p = p.rsplit(" ", 1)[0]  # "Rotator x<..>": the word glued to a value is not prefix
    p = p.strip(" .")
    return p or None


def declared(lines, n):
    """Prefixes named by a `// log: A, B` comment on line n or alone on the line above."""
    for i in (n - 1, n - 2):
        if 0 <= i < len(lines):
            m = DECLARE.search(lines[i])
            if m and (i == n - 1 or lines[i].strip().startswith("//")):
                return [d.strip() for d in m.group(1).split(",") if d.strip()]
    return []


def scan_text(path, text):
    """[(path, line, level, template, declared prefixes)] for every log call in one file."""
    # A version const would put the version into the doc and stale it at every release.
    consts = dict((k, unescape(v, False)) for k, v in CONST.findall(text) if "Version" not in k)
    masked = mask(text)
    lines = text.splitlines()
    calls = []
    for m in CALL.finditer(masked):
        arg = first_arg(text, masked, m.end())
        if arg is None or not arg.strip():
            continue
        line = text.count("\n", 0, m.start()) + 1
        calls.append((path, line, LEVELS[m.group(1)], template(arg, consts), declared(lines, line)))
    return calls


def scan(root=ROOT):
    calls = []
    for base in SCAN:
        for dirpath, dirs, files in os.walk(os.path.join(root, base)):
            dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
            for f in sorted(files):
                if f.endswith(".cs"):
                    full = os.path.join(dirpath, f)
                    with open(full, encoding="utf-8-sig") as fh:
                        rel = os.path.relpath(full, root).replace("\\", "/")
                        calls.extend(scan_text(rel, fh.read()))
    return calls


# ---------------------------------------------------------------- the doc

class Catalogue(object):
    """groups: OrderedDict prefix -> [(path, level, template, count)];
    bare: calls with no prefix [(path, line, template)]; wrong: bad declarations [(path, line, why)]."""

    def __init__(self, calls):
        groups, self.bare, self.wrong = {}, [], []
        for path, line, level, tpl, decl in calls:
            p = prefix(tpl)
            if p is not None and decl:
                self.wrong.append((path, line, "declares `%s` but starts with the literal prefix `%s`"
                                   % (", ".join(decl), p)))
            for d in decl:
                if prefix(d) != d:
                    self.wrong.append((path, line, "declares `%s`, which is not a prefix "
                                       "(words up to ':', '(' or a quote)" % d))
            names = [p] if p is not None else decl
            if not names:
                if not tpl.startswith(" "):
                    self.bare.append((path, line, tpl))
                continue
            for name in names:
                rows = groups.setdefault(name, OrderedDict())
                key = (path, level, tpl + (" *(declared)*" if p is None else ""))
                rows[key] = rows.get(key, 0) + 1
        self.groups = OrderedDict()
        for p in sorted(groups, key=lambda s: (s.lower(), s)):
            self.groups[p] = sorted((k + (n,) for k, n in groups[p].items()), key=lambda r: (r[0], r[2]))
        self.calls = len(calls)


def read_meanings(text):
    meanings, current = {}, None
    for line in text.splitlines():
        m = re.match(r"^## `(.+)`\s*$", line)
        if m:
            current = m.group(1)
        elif current is not None and line.startswith("Meaning:"):
            meanings[current] = line[len("Meaning:"):].strip()
            current = None
    return meanings


def code(text):
    return "`%s`" % text.replace("`", "'")


def render(cat, meanings):
    out = [HEADER, "%d prefixes from %d log calls.\n" % (len(cat.groups), cat.calls)]
    for p, rows in cat.groups.items():
        files = OrderedDict((r[0].split("/")[-1], None) for r in rows)
        levels = [lv for lv in LEVEL_ORDER if any(r[1] == lv for r in rows)]
        out.append("## `%s`\n" % p)
        out.append("Meaning: %s" % meanings.get(p, ""))
        out.append("Written by %s; %s.\n" % (", ".join(files), " / ".join(levels)))
        for path, level, tpl, n in rows:
            declared_mark = tpl.endswith(" *(declared)*")
            body = tpl[:-len(" *(declared)*")] if declared_mark else tpl
            out.append("- %s %s%s%s" % (level, code(body), " *(declared)*" if declared_mark else "",
                                        " (x%d)" % n if n > 1 else ""))
        out.append("")
    if cat.bare:
        out.append("## No prefix\n")
        out.append("These calls fail `--check`: give each a literal prefix.\n")
        for path, line, tpl in cat.bare:
            out.append("- %s %s" % (path, code(tpl)))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def build(root=ROOT):
    """(catalogue, new doc text, old doc text or None)."""
    path = os.path.join(root, DOC)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            old = f.read()
    cat = Catalogue(scan(root))
    return cat, render(cat, read_meanings(old or "")), old


def problems(cat, new, old):
    probs = []
    for path, line, tpl in cat.bare:
        probs.append(Problem("log call with no prefix at %s:%d: %s" % (path, line, tpl),
                             "the log is the test harness (gotcha 16): agents and e2e checks grep a line by its prefix",
                             "start the message with its mechanism's name (\"Name: \" + ...); a message built "
                             "elsewhere names its prefix in a `// log: Name` comment on the call's line; then "
                             "python scripts/log-catalogue.py and write the prefix's Meaning: line"))
    for path, line, why in cat.wrong:
        probs.append(Problem("log call at %s:%d %s" % (path, line, why),
                             "a `// log:` comment is only for a message built elsewhere and must name a real prefix",
                             "drop the comment, or make it name the prefix the line prints"))
    meanings = read_meanings(new)
    for p in cat.groups:
        if not meanings.get(p):
            probs.append(Problem("log prefix `%s` has no meaning in %s" % (p, DOC),
                                 "the catalogue says what each line means, so a check greps the right one (docs/harness.md 9a)",
                                 "python scripts/log-catalogue.py, then write the `Meaning:` line under `%s`" % p))
    if new != old:
        probs.append(Problem("%s is out of date with the log calls in src/ and patcher/" % DOC,
                             "the catalogue is generated; a changed log line changes it",
                             "python scripts/log-catalogue.py (keeps the Meaning: lines)"))
    return probs


def check(root=ROOT):
    """The problems --check reports (lint.py calls this)."""
    cat, new, old = build(root)
    return problems(cat, new, old)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail on a stale doc, an empty meaning or an unprefixed call")
    a = ap.parse_args(argv)
    cat, new, old = build()
    if a.check:
        probs = problems(cat, new, old)
        for p in probs:
            print(p, file=sys.stderr)
            print(file=sys.stderr)
        if probs:
            print("log-catalogue: %d problem(s)" % len(probs), file=sys.stderr)
            return 1
        print("log-catalogue: ok (%d prefixes)" % len(cat.groups))
        return 0
    with open(os.path.join(ROOT, DOC), "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    meanings = read_meanings(new)
    print("log-catalogue: %s - %d prefixes, %d without a meaning, %d call(s) with no prefix, %d bad declaration(s)"
          % (DOC, len(cat.groups), sum(1 for p in cat.groups if not meanings.get(p)), len(cat.bare), len(cat.wrong)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
